<?php
$env    = isset($_SERVER['_ENV']) && $_SERVER['_ENV'] == "production" ? 'prod' : 'dev';
$less   = array('style', 'bootstrap');
?><html lang=en xmlns=http://www.w3.org/1999/xhtml>
<head>
    <title>Lost Ferret Test</title>
    <meta http-equiv=Content-Type content="text/html; charset=utf-8"/>
    <meta http-equiv=Content-Type content="cache" />
    <?php foreach ($less as $file) { ?>
        <?php if ($env == "prod") { ?>
        <link rel="stylesheet" type="text/css" href="/css/<?php echo $file; ?>.css" />
        <?php } else { ?>
        <link rel="stylesheet/less" type="text/css" href="/css/<?php echo $file; ?>.less" />
            <script src="/js/less.js" type="text/javascript"></script>
        <?php } ?>
    <?php } ?>
</head>
<body>
<div id="wrapper">
    <div id="content">
        <h1>User Registration</h1>
        <div id="contentInner">
            <form role="form" id="commentForm" novalidate="novalidate">
                <div class="form-group">
                    <label for="name">Email address</label>
                    <input type="text" class="form-control" id="name" placeholder="Enter name">
                    <p class="name error hide alert-danger alert"></p>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Email address">
                    <p class="email error hide alert alert-danger"></p>
                </div>
                <div class="form-group">
                    <label for="phone">Phone Number</label>
                    <input type="text" class="form-control" id="phone" name="phone" placeholder="Phone number (numbers only, no hyphen or spaces)">
                    <p class="phone error hide alert alert-danger"></p>
                </div>
                <button type="submit" id="createUser" class="btn btn-default">Submit</button>
            </form>
            <div id="successMessage" class="alert alert-success hide">User has been created successfully</div>
            <div class="hide">
                User has been created successfully
            </div>
        </div>
    </div>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="/js/index.js"></script>
</body>
</html>